INSERT INTO TB_USER (ID, NAME, LOGIN, PASSWORD, EMAIL) VALUES (1, 'Rogério', 'rogerio', '1234','rogerionj@gmail.com');

ALTER SEQUENCE TB_USER_ID_SEQ RESTART WITH 2;

INSERT INTO TB_PROFILE (ID, DESCRIPTION) VALUES (1, 'Administrador');
INSERT INTO TB_PROFILE (ID, DESCRIPTION) VALUES (2, 'Gerente');
INSERT INTO TB_PROFILE (ID, DESCRIPTION) VALUES (3, 'Cliente');

ALTER SEQUENCE TB_PROFILE_SEQ RESTART WITH 4;

INSERT INTO TB_RESOURCE (ID, NAME, KEY) VALUES (1, 'Tela Usuário', 'usuario');
INSERT INTO TB_RESOURCE (ID, NAME, KEY) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO TB_RESOURCE (ID, NAME, KEY) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE TB_RESOURCE_SEQ RESTART WITH 4;